version: "3.1"
services:
  mongo:
    image: "mongo:4.2"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - 27027:27017
    volumes:
      - ./data:/data/db
