version: "3.1"
services:
  database:
    image: "mysql:8"
    container_name: "mysql-8"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pswd
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3309:3306"
